# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hft-system-service
spec:
  selector:
    app: hft-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
